"""empty message

Revision ID: 28913e59785d
Revises: 93da33714446
Create Date: 2020-05-18 01:53:51.223554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28913e59785d'
down_revision = '93da33714446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=600), nullable=True),
    sa.Column('question', sa.String(length=6000), nullable=True),
    sa.Column('desc', sa.String(length=5000), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('is_multi_choice', sa.Boolean(), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=50), nullable=True),
    sa.Column('choice', sa.String(length=600), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=50), nullable=True),
    sa.Column('choice', sa.String(length=600), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('survey_choice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_choice_id'], ['survey_choice.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('answer', sa.Column('quiz_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answer', 'quiz', ['quiz_id'], ['id'])
    op.drop_constraint('podcast_ibfk_1', 'podcast', type_='foreignkey')
    op.drop_column('podcast', 'user_id')
    op.drop_constraint('post_ibfk_1', 'post', type_='foreignkey')
    op.drop_column('post', 'user_id')
    op.add_column('quiz', sa.Column('date_from', sa.DateTime(), nullable=True))
    op.add_column('quiz', sa.Column('date_to', sa.DateTime(), nullable=True))
    op.add_column('quiz', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_constraint('quiz_ibfk_1', 'quiz', type_='foreignkey')
    op.drop_column('quiz', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('quiz_ibfk_1', 'quiz', 'user', ['user_id'], ['id'])
    op.drop_column('quiz', 'status')
    op.drop_column('quiz', 'date_to')
    op.drop_column('quiz', 'date_from')
    op.add_column('post', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('post_ibfk_1', 'post', 'user', ['user_id'], ['id'])
    op.add_column('podcast', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('podcast_ibfk_1', 'podcast', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'quiz_id')
    op.drop_table('survey_answer')
    op.drop_table('quiz_image')
    op.drop_table('survey_image')
    op.drop_table('survey_choice')
    op.drop_table('survey')
    # ### end Alembic commands ###