"""empty message

Revision ID: 3e2ed1dce46e
Revises: 7753893bf96b
Create Date: 2020-05-02 22:32:46.661219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e2ed1dce46e'
down_revision = '7753893bf96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=50), nullable=True),
    sa.Column('question', sa.String(length=140), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('answer', sa.Column('question_id', sa.Integer(), nullable=True))
    op.drop_constraint('answer_ibfk_1', 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'])
    op.drop_column('answer', 'quiz_id')
    op.add_column('quiz', sa.Column('body', sa.String(length=140), nullable=True))
    op.add_column('quiz', sa.Column('title', sa.String(length=140), nullable=True))
    op.drop_column('quiz', 'question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('question', mysql.VARCHAR(collation='utf8_unicode_ci', length=140), nullable=True))
    op.drop_column('quiz', 'title')
    op.drop_column('quiz', 'body')
    op.add_column('answer', sa.Column('quiz_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key('answer_ibfk_1', 'answer', 'quiz', ['quiz_id'], ['id'])
    op.drop_column('answer', 'question_id')
    op.drop_table('question')
    # ### end Alembic commands ###