"""empty message

Revision ID: 7104bbee76d9
Revises: 9ff733523cbd
Create Date: 2020-06-27 01:10:45.788653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7104bbee76d9'
down_revision = '9ff733523cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_ibfk_3', 'image', type_='foreignkey')
    op.drop_column('image', 'district_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('district_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('image_ibfk_3', 'image', 'district', ['district_id'], ['id'])
    # ### end Alembic commands ###