"""empty message

Revision ID: 716f2d5710af
Revises: 2fe9cbe37801
Create Date: 2020-06-24 20:35:08.238858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716f2d5710af'
down_revision = '2fe9cbe37801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('election', sa.Column('total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('election', 'total')
    # ### end Alembic commands ###