"""empty message

Revision ID: 924ccc0bb733
Revises: 4bfc2ee9f6cd
Create Date: 2020-05-16 02:43:11.602853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924ccc0bb733'
down_revision = '4bfc2ee9f6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.String(length=100000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body')
    # ### end Alembic commands ###