"""empty message

Revision ID: 93da33714446
Revises: fbdd348e335d
Create Date: 2020-05-17 18:53:40.762276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93da33714446'
down_revision = 'fbdd348e335d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast', 'name')
    # ### end Alembic commands ###