"""empty message

Revision ID: caf433910dd0
Revises: 7678d52398b5
Create Date: 2020-05-15 01:02:29.058586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'caf433910dd0'
down_revision = '7678d52398b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('public_id', table_name='user')
    op.drop_column('user', 'public_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('public_id', 'user', ['public_id'], unique=True)
    # ### end Alembic commands ###