"""empty message

Revision ID: f0cd5492139b
Revises: db9c3f284127
Create Date: 2020-05-16 13:04:15.290590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0cd5492139b'
down_revision = 'db9c3f284127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary', sa.Column('word_en', sa.String(length=600), nullable=True))
    op.add_column('dictionary', sa.Column('word_mn', sa.String(length=6000), nullable=True))
    op.drop_column('dictionary', 'mn')
    op.drop_column('dictionary', 'en')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary', sa.Column('en', mysql.VARCHAR(collation='utf8_unicode_ci', length=600), nullable=True))
    op.add_column('dictionary', sa.Column('mn', mysql.VARCHAR(collation='utf8_unicode_ci', length=6000), nullable=True))
    op.drop_column('dictionary', 'word_mn')
    op.drop_column('dictionary', 'word_en')
    # ### end Alembic commands ###