"""empty message

Revision ID: fbdd348e335d
Revises: f0cd5492139b
Create Date: 2020-05-16 14:46:14.037195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbdd348e335d'
down_revision = 'f0cd5492139b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('post', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_pinned')
    op.drop_column('post', 'is_featured')
    # ### end Alembic commands ###